// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Builders from "@discordjs/builders";

var helpMessage = "```\nThis channel is used to post challenges in the SHE community. Please refrain fron\nposting non-challenge related content.\nIf you would like to reply to a challenge, please create a thread!\n\nChallenges must include a valid link to a challenge or they will be deleted.\n\nExample: I did a backflip!\nhttps://www.youtube.com/watch?v=dQw4w9WgXcQ\n\n```";

var data = new Builders.SlashCommandBuilder().setName("help").setDescription("Explain the Challenge Feed Channel Rules");

function execute(interaction) {
  return interaction.reply(helpMessage, {
              ephemeral: true
            });
}

export {
  helpMessage ,
  data ,
  execute ,
  
}
/* data Not a pure module */
